# Develop Merge Action
# ````````````````````````````````````````````````````````````````````
# keep the 'develop' branch up-to-date with master, ensuring hotfixes
# are automatically merged into the develop branch
#
# occurs on push actions
name: "Develop Branch Merge Action"

on:
  push:
    branches: 'master'
  pull_request:
    types: [closed]
jobs:
  merge-master-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: Merge
        uses: robotology/gh-action-nightly-merge@v1.2.0
        with:
          stable_branch: 'master'
          development_branch: 'develop'
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
